
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class modul1_1 extends javax.swing.JFrame {

    /**
     * Creates new form modul1_1
     */
    public modul1_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eAlasan = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        eNIM = new javax.swing.JTextField();
        eAlamat = new javax.swing.JTextField();
        wanita = new javax.swing.JRadioButton();
        pria = new javax.swing.JRadioButton();
        eTelp = new javax.swing.JTextField();
        eProdi = new javax.swing.JComboBox<>();
        sangat = new javax.swing.JCheckBox();
        lumayan = new javax.swing.JCheckBox();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("FORMULIR PENDAFTARAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 20, 164, 18);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("UKM INFORMATION TECHNOLOGY CENTER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 40, 268, 18);

        jLabel3.setText("NAMA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(96, 120, 40, 16);

        jLabel5.setText("NIM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(98, 149, 23, 16);

        jLabel6.setText("ALAMAT");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(98, 177, 47, 16);

        jLabel7.setText("JENIS KELAMIN");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(98, 205, 110, 16);

        jLabel8.setText("NO TELP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(98, 233, 100, 16);

        jLabel9.setText("PRODI");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(98, 261, 90, 16);

        jLabel10.setText("YAKIN DAFTAR?");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(98, 288, 120, 16);

        eAlasan.setColumns(20);
        eAlasan.setRows(5);
        jScrollPane1.setViewportView(eAlasan);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(98, 318, 297, 66);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("UNIVERSITAS TRUNOJOYO MADURA");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 60, 226, 18);
        jPanel1.add(eNama);
        eNama.setBounds(246, 118, 152, 22);
        jPanel1.add(eNIM);
        eNIM.setBounds(246, 146, 152, 22);
        jPanel1.add(eAlamat);
        eAlamat.setBounds(246, 174, 152, 22);

        buttonGroup1.add(wanita);
        wanita.setText("Wanita");
        jPanel1.add(wanita);
        wanita.setBounds(246, 203, 70, 21);

        buttonGroup1.add(pria);
        pria.setText("Pria");
        jPanel1.add(pria);
        pria.setBounds(325, 203, 70, 21);
        jPanel1.add(eTelp);
        eTelp.setBounds(246, 230, 150, 22);

        eProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Prodi", "Sistem Informasi", "Teknik Informatika", "Teknik Mesin", "Teknik Elektro", "Teknik Mekatronika", "Teknik Industri" }));
        jPanel1.add(eProdi);
        eProdi.setBounds(245, 258, 151, 22);

        buttonGroup2.add(sangat);
        sangat.setText("Sangat");
        sangat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sangatActionPerformed(evt);
            }
        });
        jPanel1.add(sangat);
        sangat.setBounds(245, 286, 70, 20);

        buttonGroup2.add(lumayan);
        lumayan.setText("Lumayan");
        jPanel1.add(lumayan);
        lumayan.setBounds(321, 286, 80, 20);

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bSimpan);
        bSimpan.setBounds(120, 400, 74, 23);

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus);
        bHapus.setBounds(210, 400, 72, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utm.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 10, 80, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoitc.jpeg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 10, 77, 80);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2.jpeg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 490, 100);

        bExit.setText("EXIT");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel1.add(bExit);
        bExit.setBounds(300, 400, 80, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar1.jpeg"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 100, 490, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        eNama.setText("");
        eNIM.setText("");
        eAlamat.setText("");
        buttonGroup1.clearSelection();
        eTelp.setText("");
        eProdi.setSelectedIndex(0);
        buttonGroup2.clearSelection();
        eAlasan.setText("");
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String nama = eNama.getText();
        String nim = eNIM.getText();
        String alamat = eAlamat.getText();
        String jenisKelamin = "Wanita"; //inialisasi secara default
            if(pria.isSelected()){
               jenisKelamin = "Pria";
            }
        String telp = eTelp.getText();
        String prodi = (String) eProdi.getSelectedItem(); //mengambil pilihan
        String yakinDaftar = "Sangat";
            if(lumayan.isSelected()){
               yakinDaftar = "Lumayan";
            }
        String alasan = eAlasan.getText();

        JOptionPane.showMessageDialog(null, "Nama : "+ nama + "\n NIM : " + nim+  "\n Alamat : " + alamat + 
            "\n Jenis Kelamin : " + jenisKelamin + "\n Telp : " + telp + "\n Prodi : " + prodi + "\n Yakin Daftar? : " + yakinDaftar +"\n Alasan : " + alasan);
    }//GEN-LAST:event_bSimpanActionPerformed

    private void sangatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sangatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sangatActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul1_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField eAlamat;
    private javax.swing.JTextArea eAlasan;
    private javax.swing.JTextField eNIM;
    private javax.swing.JTextField eNama;
    private javax.swing.JComboBox<String> eProdi;
    private javax.swing.JTextField eTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lumayan;
    private javax.swing.JRadioButton pria;
    private javax.swing.JCheckBox sangat;
    private javax.swing.JRadioButton wanita;
    // End of variables declaration//GEN-END:variables
}
